spring:
  datasource:
    url: jdbc:h2:~/contentree
    driverClassName: org.h2.Driver
    username: sye
    password: 1004

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate.ddl-auto: update


  h2:
    console:
      enabled: true
      path: /h2-console
  ## JWT Custom
  jwt:
    secret:
      signature: "TOYPROJECTSONGYOUNGEUNLOGINSERVICE"

  logging:
    level:
      org.springframework.web: debug
      org.springframework.security: debug